import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { log } from 'node:console';

@Component({
  selector: 'app-emojis',
  standalone: true,
  imports: [CommonModule,RouterLink],
  templateUrl: './emojis.component.html',
  styleUrls: ['./emojis.component.css']
})
export class EmojisComponent implements OnInit {
  //   emojis: string[] = [
  //  'grin',
  //     'beam',
  //     'joy',
  //     'laugh',
  //     'grin_1',
  //     'grin_2',
  //     'grin_3',
  //     'grin_4',
  //     'wink',
  //     'smile',
  //     'savor',
  //     'smile_1',
  //     'smile_2',
  //     'blow_kiss',
  //     'kiss',
  //     'kiss_1',
  //     'kiss_2',
  //     'smile_3',
  //     'smile_4',
  //     'hug_face',
  //     'star_struck',
      // 'think',
      // 'eyebrow',
      // 'neutral',
      // 'expressionless',
      // 'face',
      // 'smirk',
      // 'face',
      // 'sad',
      // 'mouth_open',
      // 'mouth_zip',
      // 'hushed_face',
      // 'sleepy_face',
      // 'tired',
      // 'sleeping',
      // 'relieved',
      // 'wink_1',
      // 'squint_tongue',
      // 'drool',
      // 'unamused',
      // 'downcast',
      // 'pensive',
      // 'confused',
      // 'face_down',
      // 'money_mouth',
      // 'astonished',
      // 'frowning',
      // 'frown',
      // 'confounded',
      // 'disappointed',
      // 'worried',
      // 'nose',
      // 'crying',
      // 'wail',
      // 'frown',
      // 'anguished',
      // 'fearful',
      // 'weary',
      // 'exploding',
      // 'grimace',
      // 'anxious',
      // 'screaming',
      // 'flushed',
      // 'zany_face',
      // 'dizzy',
      // 'poute',
      // 'angry',
      // 'nauseated',
      // 'vomiting',
      // 'sneezing',
      // 'cowboy',
      // 'lying',
      // 'nerd',
      // 'angry_1',
      // 'clown',
      // 'ogre',
      // 'goblin',
      // 'skull',
      // 'ghost',
      // 'alien',
      // 'thermometer',
      // 'robot',
      // 'poo',
      // 'baby',
      // 'child',
      // 'boy',
      // 'girl',
      // 'person',
      // 'man',
      // 'beard',
      // 'woman',
      // 'older_person',
      // 'old_man',
      // 'old_woman',
      // 'monkey_1',
      // 'monkey_2',
      // 'monkey_3',
      // 'police',
      // 'detective',
      // 'guard',
      // 'prince',
      // 'princess',
      // 'baby_angel',
      // 'Santa_Claus',
      // 'mage',
      // 'fairy',
      // 'vampire',
      // 'merperson',
      // 'merman',
      // 'mermaid',
      // 'elf',
      // 'genie',
      // 'man_genie',
      // 'woman_genie',
      // 'zombie',
      // 'person_frown',
      // 'man_frown',
      // 'woman_frown',
      // 'person_pout',
      // 'man_pout',
      // 'woman_pout',
      // 'person_no',
      // 'man_no',
      // 'woman_no',
      // 'person_ok',
      // 'man_ok',
      // 'woman_ok',
      // 'person_tip',
      // 'man_tip',
      // 'woman_tip',
      // 'person_hand',
      // 'man_hand',
      // 'woman_hand',
      // 'person_bow',
      // 'man_bow',
      // 'woman_bow',
      // 'person_facepalm',
      // 'man_facepalm',
      // 'woman_facepalm',
      // 'person_shrug',
      // 'man_shrug',
      // 'woman_shrug',
      // 'person_walk',
      // 'man_walk',
      // 'woman_walk',
      // 'person_run',
      // 'man_run',
      // 'woman_run',
      // 'woman_dance',
      // 'man_dance',
      // 'person_climb',
      // 'man_climb',
      // 'woman_climb',
      // 'person_lotus',
      // 'man_lotus',
      // 'woman_lotus',
      // 'shower',
      // 'nap',
      // 'horse_racing',
      // 'skier',
      // 'snowboarder',
      // 'person_surfing',
      // 'man_surfing',
      // 'woman_surfing',
      // 'person_swim',
      // 'man_swim',
      // 'woman_swim',
      // 'person_lift',
      // 'man_lift',
      // 'woman_lift',
      // 'person_cycle',
      // 'race_car',
      // 'motorcycle',
      // 'person_cartwheel',
      // 'man_cartwheel',
      // 'woman_cartwheel',
      // 'people_wrestle',
      // 'men_wrestle',
      // 'women_wrestle',
      // 'person_juggle',
      // 'man_juggle',
      // 'woman_juggle',
      // 'couple_1',
      // 'kissing',
      // 'kissing_1',
      // 'couple',
      // 'family',
      // 'selfie',
      // 'biceps',
      // 'sure',
      // 'fu',
      // 'victory',
      // 'fingers_',
      // 'vulcan_salute',
      // 'call_me',
      // 'raised_hand',
      // 'ok',
      // 'thumbs_up',
      // 'thumbs_down',
      // 'raised_fist',
      // 'fist',
      // 'left_fist',
      // 'right_fist',
      // 'wave',
      // 'love_your',
      // 'write',
      // 'clap',
      // 'open_hands',
      // 'raising_hands',
      // 'palms_up',
      // 'folded_hands',
      // 'handshake',
      // 'nail_polish',
      // 'ear',
      // 'nose',
      // 'footprints',
      // 'eyes',
      // 'eye',
      // 'brain',
      // 'mouth',
      // 'kiss_mark',
      // 'heart_beat',
      // 'revolving_hearts',
      // 'two_hearts',
      // 'broken_heart',
      // 'heart',
      // 'anger_symbol',
      // 'bomb',
      // 'collision',
      // 'sweat',
      // 'dizzy_1',
      // 'speech_balloon',
      // 'anger',
      // 'thought',
      // 'hole',
      // 'glasses',
      // 'sunglasses',
      // 'neck_tie',
      // 't_shirt',
      // 'jeans',
      // 'scarf',
      // 'gloves',
      // 'coat',
      // 'socks',
      // 'dress',
      // 'kimono',
      // 'bikini',
      // 'women_cloth',
      // 'purse',
      // 'handbag',
      // 'clutch_bag',
      // 'shopping_bag',
      // 'backpack',
      // 'man_shoe',
      // 'running_shoe',
      // 'heeled_shoe',
      // 'woman_boot',
      // 'crown',
      // 'woman_hat',
      // 'top_hat',
      // 'graduation_cap',
      // 'billed_cap',
      // 'rescue_helmet',
      // 'lipstick',
      // 'ring',
      // 'gem_stone',
      // 'monkey_face',
      // 'monkey',
      // 'gorilla',
      // 'dog_face',
      // 'dog',
      // 'poodle',
      // 'wolf_face',
      // 'fox_face',
      // 'cat_face',
      // 'cat',
      // 'lion',
      // 'tiger_face',
      // 'tiger',
      // 'leopard',
      // 'horse_face',
      // 'horse',
      // 'unicorn',
      // 'zebra',
      // 'deer',
      // 'cow_face',
      // 'ox',
      // 'water_buffalo',
      // 'cow',
      // 'pig_face',
      // 'pig',
      // 'boar',
      // 'pig_nose',
      // 'ram',
      // 'ewe',
      // 'goat',
      // 'camel',
      // 'camel_2',
      // 'giraffe',
      // 'elephant',
      // 'rhinoceros',
      // 'mouse_face',
      // 'mouse',
      // 'rat',
      // 'hamster',
      // 'rabbit_face',
      // 'rabbit',
      // 'chipmunk',
      // 'hedgehog',
      // 'bat',
      // 'bear_face',
      // 'koala',
      // 'panda',
      // 'paw',
      // 'turkey',
      // 'chicken',
      // 'rooster',
      // 'chick',
      // 'chick_1',
      // 'chick_2',
      // 'bird',
      // 'penguin',
      // 'dove',
      // 'eagle',
      // 'duck',
      // 'owl',
      // 'frog',
      // 'crocodile',
      // 'turtle',
      // 'lizard',
      // 'snake',
      // 'dragon_face',
      // 'dragon',
      // 'sauropod',
      // 'spouting_whale',
      // 'whale',
      // 'dolphin',
      // 'fish',
      // 'fish_1',
      // 'blowfish',
      // 'shark',
      // 'octopus',
      // 'spiral_shell',
      // 'butterfly',
      // 'bug',
      // 'ant',
      // 'honeybee',
      // 'beetle',
      // 'cricket',
      // 'spider',
      // 'spider_web',
      // 'scorpion',
      // 'bouquet',
      // 'cherry_blossom',
      // 'rosette',
      // 'rose',
      // 'wilted_flower',
      // 'hibiscus',
      // 'sunflower',
      // 'blossom',
      // 'tulip',
      // 'seedling',
      // 'tree',
      // 'palm_tree',
      // 'cactus',
      // 'herb',
      // 'shamrock',
      // 'maple_leaf',
      // 'fallen_leaf',
      // 'leaf_in_wind',
      // 'grapes',
      // 'melon',
      // 'watermelon',
      // 'tangerine',
      // 'lemon',
      // 'banana',
      // 'pineapple',
      // 'apple',
      // 'pear',
      // 'peach',
      // 'cherries',
      // 'strawberry',
      // 'kiwi_fruit',
      // 'tomatoes',
      // 'coconut',
      // 'avocado',
      // 'eggplant',
      // 'potato',
      // 'carrot',
      // 'pepper',
      // 'cucumber',
      // 'broccoli',
      // 'mushroom',
      // 'peanuts',
      // 'chestnut',
      // 'bread',
      // 'croissant',
      // 'baguette',
      // 'pretzel',
      // 'pancakes',
      // 'cheese',
      // 'meat',
      // 'poultry',
      // 'meat_cut',
      // 'bacon',
      // 'hamburger',
      // 'fries',
      // 'pizza',
      // 'hot_dog',
      // 'sandwich',
      // 'taco',
      // 'burrito',
      // 'flatbread',
      // 'egg',
      // 'cooking',
      // 'pan_of_food',
      // 'food',
      // 'spoon',
      // 'salad',
      // 'popcorn',
      // 'canned_food',
      // 'bento_box',
      // 'curry_rice',
      // 'steaming_bowl',
      // 'spaghetti',
      // 'roasted_sweet_potato',
      // 'oden',
      // 'sushi',
      // 'fried_shrimp',
      // 'dango',
      // 'dumpling',
      // 'fortune_cookie',
      // 'takeout_box',
      // 'crab',
      // 'shrimp',
      // 'squid',
      // 'soft_ice_cream',
      // 'shaved_ice',
      // 'ice_cream',
      // 'doughnut',
      // 'cookie',
      // 'birthday_cake',
      // 'shortcake',
      // 'pie',
      // 'chocolate_bar',
      // 'candy',
      // 'lollipop',
      // 'custard',
      // 'honey_pot',
      // 'baby_bottle',
      // 'milk',
      // 'teacup',
      // 'sake',
      // 'wine',
      // 'cocktail',
      // 'tropical_drink',
      // 'beer_mug',
      // 'clinking_glasses',
      // 'tumbler_glass',
      // 'chopsticks',
      // 'cutlery',
      // 'fork_knife',
      // 'spoon',
      // 'kitchen_knife',
      // 'amphora',
      // 'globe_africa',
      // 'snow_capped',
      // 'mountain',
      // 'volcano',
      // 'camping',
      // 'beach',
      // 'desert',
      // 'stadium',
      // 'building',
      // 'houses',
      // 'house',
      // 'home',
      // 'office_building',
      // 'post_office',
      // 'hospital',
      // 'bank',
      // 'hotel',
      // 'convenience_store',
      // 'school',
      // 'department_store',
      // 'factory',
      // 'Japanese_castle',
      // 'castle',
      // 'statue_of_Liberty',
      // 'church',
      // 'mosque',
      // 'synagogue',
      // 'fountain',
      // 'tent',
      // 'hot_springs',
      // 'ferris_wheel',
      // 'roller_coaster',
      // 'barber_pole',
      // 'circus_tent',
      // 'railway_car',
      // 'train',
      // 'metro',
      // 'light_rail',
      // 'station',
      // 'tram',
      // 'monorail',
      // 'railway',
      // 'tram',
      // 'bus',
      // 'oncoming_bus',
      // 'ambulance',
      // 'fire_engine',
      // 'taxi',
      // 'oncoming_taxi',
      // 'tractor',
      // 'bicycle',
      // 'kick_scooter',
      // 'motor_scooter',
      // 'motorway',
      // 'railway_track',
      // 'stop_sign',
      // 'construction',
      // 'anchor',
      // 'sailboat',
      // 'canoe',
      // 'speedboat',
      // 'passenger_ship',
      // 'ferry',
      // 'motor_boat',
      // 'ship',
      // 'airplane',
      // 'small_airplane',
      // 'departure',
      // 'arrival',
      // 'seat',
      // 'helicopter',
      // 'cableway',
      // 'tramway',
      // 'satellite',
      // 'rocket',
      // 'flying_saucer',
      // 'hourglass',
      // 'hourglass_1',
      // 'watch',
      // 'alarm_clock',
      // 'stopwatch',
      // 'new_moon',
      // 'thermometer',
      // 'sun',
      // 'star',
      // 'glowing_star',
      // 'cloud',
      // 'tornado',
      // 'cyclone',
      // 'rainbow',
      // 'closed_umbrella',
      // 'umbrella',
      // 'high_voltage',
      // 'snowflake',
      // 'comet',
      // 'fire',
      // 'droplet',
      // 'jack-o-lantern',
      // 'christmas_tree',
      // 'sparkles',
      // 'balloon',
      // 'party_popper',
      // 'wind_chime',
      // 'ribbon',
      // 'gift',
      // 'tickets',
      // 'medal',
      // 'trophy',
      // 'medal_4',
      // 'medal_1',
      // 'medal_2',
      // 'medal_3',
      // 'soccer_ball',
      // 'baseball',
      // 'basketball',
      // 'volleyball',
      // 'american_football',
      // 'rugby',
      // 'tennis',
      // 'bowling',
      // 'cricket',
      // 'hockey',
      // 'ice_hockey',
      // 'ping_pong',
      // 'badminton',
      // 'boxing_glove',
      // 'goal_net',
      // 'flag_in_hole',
      // 'ice_skate',
      // 'fishing_pole',
      // 'skis',
      // 'sled',
      // 'direct_hit',
      // 'crystal_ball',
      // 'video_game',
      // 'joystick',
      // 'game_die',
      // 'chess_pawn',
      // 'megaphone',
      // 'postal_horn',
      // 'bell',
      // 'microphone',
      // 'headphone',
      // 'saxophone',
      // 'guitar',
      // 'musical_keyboard',
      // 'trumpet',
      // 'violin',
      // 'drum',
      // 'mobile',
      // 'telephone',
      // 'pager',
      // 'battery',
      // 'laptop',
      // 'desktop',
      // 'keyboard',
      // 'mouse',
      // 'trackball',
      // 'camera',
      // 'candle',
      // 'bulb',
      // 'flashlight',
      // 'notebook',
      // 'book',
      // 'books',
      // 'notebook',
      // 'ledger',
      // 'bookmark',
      // 'label',
      // 'money_bag',
      // 'yen',
      // 'dollar',
      // 'euro',
      // 'pound',
      // 'credit_card',
      // 'dollar_sign',
      // 'envelope',
      // 'email',
      // 'outbox',
      // 'inbox',
      // 'package',
      // 'black_nib',
      // 'fountain_pen',
      // 'pen',
      // 'paintbrush',
      // 'memo',
      // 'briefcase',
      // 'file_folder',
      // 'calendar',
      // 'card_index',
      // 'clipboard',
      // 'pushpin',
      // 'paperclip',
      // 'ruler',
      // 'scissors',
      // 'cabinet',
      // 'wastebasket',
      // 'locked',
      // 'unlocked',
      // 'key',
      // 'old_key',
      // 'hammer',
      // 'pick',
      // 'wrench',
      // 'dagger',
      // 'swords',
      // 'pistol',
      // 'bow',
      // 'shield',
      // 'wrench',
      // 'nut_bolt',
      // 'gear',
      // 'scale',
      // 'link',
      // 'chains',
      // 'microscope',
      // 'telescope',
      // 'satellite',
      // 'syringe',
      // 'pill',
      // 'door',
      // 'bed',
      // 'couch_lamp',
      // 'toilet',
      // 'shower',
      // 'bathtub'
    //  ];

  emojis: { name: string, emoji: string }[] = [
    { name: 'grin', emoji: '\u{1F600}' },
    { name: 'beam', emoji: '\u{1F601}' },
    { name: 'joy', emoji: '\u{1F602}' },
    { name: 'laugh', emoji: '\u{1F923}' },
    { name: 'grin_1', emoji: '\u{1F603}' },
    { name: 'grin_2', emoji: '\u{1F604}' },
    { name: 'grin_3', emoji: '\u{1F605}' },
    { name: 'grin_4', emoji: '\u{1F606}' },
    { name: 'wink', emoji: '\u{1F609}' },
    { name: 'smile', emoji: '\u{1F60A}' },
    { name: 'savor', emoji: '\u{1F60B}' },
    { name: 'smile_1', emoji: '\u{1F60E}' },
    { name: 'smile_2', emoji: '\u{1F60D}' },
    { name: 'blow_kiss', emoji: '\u{1F618}' },
    { name: 'kiss', emoji: '\u{1F617}' },
    { name: 'kiss_1', emoji: '\u{1F619}' },
    { name: 'kiss_2', emoji: '\u{1F61A}' },
    { name: 'smile_3', emoji: '\u{263A}' }, // ☺
    { name: 'smile_4', emoji: '\u{1F642}' },
    { name: 'hug_face', emoji: '\u{1F917}' },
    { name: 'star_struck', emoji: '\u{1F929}' },
    { name: 'think', emoji: '\u{1F914}' },
    { name: 'eyebrow', emoji: '\u{1F928}' },
    { name: 'neutral', emoji: '\u{1F610}' },
    { name: 'expressionless', emoji: '\u{1F611}' },
    { name: 'mouth_1', emoji: '\u{1F636}' },
    { name: 'face', emoji: '\u{1F644}' },
    { name: 'smirk', emoji: '\u{1F60F}' },
    { name: 'face_1', emoji: '\u{1F623}' },
    { name: 'sad', emoji: '\u{1F625}' },
    { name: 'mouth_open', emoji: '\u{1F62E}' },
    { name: 'mouth_zip', emoji: '\u{1F910}' },
    { name: 'hushed_face', emoji: '\u{1F62F}' },
    { name: 'sleepy_face', emoji: '\u{1F62A}' },
    { name: 'tired', emoji: '\u{1F62B}' },
    { name: 'sleeping', emoji: '\u{1F634}' },
    { name: 'relieved', emoji: '\u{1F60C}' },
    { name: 'tongue_1', emoji: '\u{1F61B}' },
    { name: 'wink_1', emoji: '\u{1F61C}' },
    { name: 'squint_tongue', emoji: '\u{1F61D}' },
    { name: 'drool', emoji: '\u{1F924}' },
    { name: 'unamused', emoji: '\u{1F612}' },
    { name: 'downcast', emoji: '\u{1F613}' },
    { name: 'pensive', emoji: '\u{1F614}' },
    { name: 'confused', emoji: '\u{1F615}' },
    { name: 'face_down', emoji: '\u{1F643}' },
    { name: 'money_mouth', emoji: '\u{1F911}' },
    { name: 'astonished', emoji: '\u{1F632}' },
    { name: 'frowning', emoji: '\u{2639}' }, // ☹
    { name: 'frown', emoji: '\u{1F641}' },
    { name: 'confounded', emoji: '\u{1F616}' },
    { name: 'disappointed', emoji: '\u{1F61E}' },
    { name: 'worried', emoji: '\u{1F61F}' },
    { name: 'nose_1', emoji: '\u{1F624}' },
    { name: 'crying', emoji: '\u{1F622}' },
    { name: 'wail', emoji: '\u{1F62D}' },
    { name: 'frown_1', emoji: '\u{1F626}' },
    { name: 'anguished', emoji: '\u{1F627}' },
    { name: 'fearful', emoji: '\u{1F628}' },
    { name: 'weary', emoji: '\u{1F629}' },
    { name: 'exploding', emoji: '\u{1F92F}' },
    { name: 'grimace', emoji: '\u{1F62C}' },
    { name: 'anxious', emoji: '\u{1F630}' },
    { name: 'screaming', emoji: '\u{1F631}' },
    { name: 'flushed', emoji: '\u{1F633}' },
    { name: 'zany_face', emoji: '\u{1F92A}' },
    { name: 'dizzy', emoji: '\u{1F635}' },
    { name: 'poute', emoji: '\u{1F621}' },
    { name: 'angry', emoji: '\u{1F620}' },
    { name: 'nauseated', emoji: '\u{1F922}' },
    { name: 'vomiting', emoji: '\u{1F92E}' },
    { name: 'sneezing', emoji: '\u{1F927}' },
    { name: 'cowboy', emoji: '\u{1F920}' },
    { name: 'partying', emoji: '\u{1F973}' },
    { name: 'pleading', emoji: '\u{1F97A}' },
    { name: 'lying', emoji: '\u{1F925}' },
    { name: 'nerd', emoji: '\u{1F913}' },
    { name: 'angry_1', emoji: '\u{1F47F}' },
    { name: 'clown', emoji: '\u{1F921}' },
    { name: 'ogre', emoji: '\u{1F479}' },
    { name: 'goblin', emoji: '\u{1F47A}' },
    { name: 'skull', emoji: '\u{1F480}' },
    { name: 'ghost', emoji: '\u{1F47B}' },
    { name: 'alien', emoji: '\u{1F47D}' },
    { name: 'thermo', emoji: '\u{1F912}' },
    { name: 'robot', emoji: '\u{1F916}' },
    { name: 'poo', emoji: '\u{1F4A9}' },
    { name: 'baby', emoji: '\u{1F476}' },
    { name: 'child', emoji: '\u{1F9D2}' },
    { name: 'boy', emoji: '\u{1F466}' },
    { name: 'girl', emoji: '\u{1F467}' },
    { name: 'person', emoji: '\u{1F9D1}' },
    { name: 'man', emoji: '\u{1F468}' },
    { name: 'beard', emoji: '\u{1F9D4}' },
    { name: 'woman', emoji: '\u{1F469}' },
    { name: 'older_person', emoji: '\u{1F9D3}' },
    { name: 'old_man', emoji: '\u{1F474}' },
    { name: 'old_woman', emoji: '\u{1F475}' },
    { name: 'monkey_1', emoji: '\u{1F648}' },
    { name: 'monkey_2', emoji: '\u{1F649}' },
    { name: 'monkey_3', emoji: '\u{1F64A}' },
    { name: 'police', emoji: '\u{1F46E}' },
    { name: 'detective', emoji: '\u{1F575}' },
    { name: 'guard', emoji: '\u{1F482}' },
    { name: 'prince', emoji: '\u{1F934}' },
    { name: 'princess', emoji: '\u{1F478}' },
    { name: 'baby_angel', emoji: '\u{1F47C}' },
    { name: 'Santa_Claus', emoji: '\u{1F385}' },
    { name: 'superhero', emoji: '\u{1F9B8}' },
    { name: 'mage', emoji: '\u{1F9D9}' },
    { name: 'fairy', emoji: '\u{1F9DA}' },
    { name: 'vampire', emoji: '\u{1F9DB}' },
    { name: 'merperson', emoji: '\u{1F9DC}' },
    { name: 'merman', emoji: '\u{1F9DC}' },
    { name: 'mermaid', emoji: '\u{1F9DC}' },
    { name: 'elf', emoji: '\u{1F9DD}' },
    { name: 'man_elf', emoji: '\u{1F9DD}' },
    { name: 'woman_elf', emoji: '\u{1F9DD}' },
    { name: 'genie', emoji: '\u{1F9DE}' },
    { name: 'man_genie', emoji: '\u{1F9DE}' },
    { name: 'woman_genie', emoji: '\u{1F9DE}' },
    { name: 'zombie', emoji: '\u{1F9DF}' },
    { name: 'person_frown', emoji: '\u{1F64D}' },
    { name: 'man_frown', emoji: '\u{1F64D}' },
    { name: 'woman_frown', emoji: '\u{1F64D}' },
    { name: 'person_pout', emoji: '\u{1F64E}' },
    { name: 'man_pout', emoji: '\u{1F64E}' },
    { name: 'woman_pout', emoji: '\u{1F64E}' },
    { name: 'person_no', emoji: '\u{1F645}' },
    { name: 'man_no', emoji: '\u{1F645}' },
    { name: 'woman_no', emoji: '\u{1F645}' },
    { name: 'person_ok', emoji: '\u{1F646}' },
    { name: 'man_ok', emoji: '\u{1F646}' },
    { name: 'woman_ok', emoji: '\u{1F646}' },
    { name: 'person_tip', emoji: '\u{1F481}' },
    { name: 'man_tip', emoji: '\u{1F481}' },
    { name: 'woman_tip', emoji: '\u{1F481}' },
    { name: 'person_hand', emoji: '\u{1F64B}' },
    { name: 'man_hand', emoji: '\u{1F64B}' },
    { name: 'woman_hand', emoji: '\u{1F64B}' },
    { name: 'person_bow', emoji: '\u{1F647}' },
    { name: 'man_bow', emoji: '\u{1F647}' },
    { name: 'woman_bow', emoji: '\u{1F647}' },
    { name: 'person_facepalm', emoji: '\u{1F926}' },
    { name: 'man_facepalm', emoji: '\u{1F926}' },
    { name: 'woman_facepalm', emoji: '\u{1F926}' },
    { name: 'person_shrug', emoji: '\u{1F937}' },
    { name: 'man_shrug', emoji: '\u{1F937}' },
    { name: 'woman_shrug', emoji: '\u{1F937}' },
    { name: 'person_walk', emoji: '\u{1F6B6}' },
    { name: 'man_walk', emoji: '\u{1F6B6}' },
    { name: 'woman_walk', emoji: '\u{1F6B6}' },
    { name: 'person_run', emoji: '\u{1F3C3}' },
    { name: 'man_run', emoji: '\u{1F3C3}' },
    { name: 'woman_run', emoji: '\u{1F3C3}' },
    { name: 'woman_dance', emoji: '\u{1F483}' },
    { name: 'man_dance', emoji: '\u{1F57A}' },
    { name: 'person_climb', emoji: '\u{1F9D7}' },
    { name: 'man_climb', emoji: '\u{1F9D7}' },
    { name: 'woman_climb', emoji: '\u{1F9D7}' },
    { name: 'person_lotus', emoji: '\u{1F9D8}' },
    { name: 'man_lotus', emoji: '\u{1F9D8}' },
    { name: 'woman_lotus', emoji: '\u{1F9D8}' },
    { name: 'shower', emoji: '\u{1F6C0}' },
    { name: 'nap', emoji: '\u{1F6CC}' },
    { name: 'horse_racing', emoji: '\u{1F3C7}' },
    { name: 'skier', emoji: '\u{26F7}' },
    { name: 'snowboarder', emoji: '\u{1F3C2}' },
    { name: 'person_surfing', emoji: '\u{1F3C4}' },
    { name: 'man_surfing', emoji: '\u{1F3C4}' },
    { name: 'woman_surfing', emoji: '\u{1F3C4}' },
    { name: 'person_swim', emoji: '\u{1F3CA}' },
    { name: 'man_swim', emoji: '\u{1F3CA}' },
    { name: 'woman_swim', emoji: '\u{1F3CA}' },
    { name: 'person_lift', emoji: '\u{1F3CB}' },
    { name: 'man_lift', emoji: '\u{1F3CB}' },
    { name: 'woman_lift', emoji: '\u{1F3CB}' },
    { name: 'person_cycle', emoji: '\u{1F6B4}' },
    { name: 'race_car', emoji: '\u{1F3CE}' },
    { name: 'motorcycle', emoji: '\u{1F3CD}' },
    { name: 'person_cartwheel', emoji: '\u{1F938}' },
    { name: 'man_cartwheel', emoji: '\u{1F938}' },
    { name: 'woman_cartwheel', emoji: '\u{1F938}' },
    { name: 'people_wrestle', emoji: '\u{1F93C}' },
    { name: 'men_wrestle', emoji: '\u{1F93C}' },
    { name: 'women_wrestle', emoji: '\u{1F93C}' },
    { name: 'person_juggle', emoji: '\u{1F939}' },
    { name: 'man_juggle', emoji: '\u{1F939}' },
    { name: 'woman_juggle', emoji: '\u{1F939}' },
    { name: 'couple_1', emoji: '\u{1F46B}' },
    { name: 'kissing', emoji: '\u{1F48F}' },
    { name: 'kissing_1', emoji: '\u{1F469}' },
    { name: 'couple', emoji: '\u{1F491}' },
    { name: 'family', emoji: '\u{1F46A}' },
    { name: 'selfie', emoji: '\u{1F933}' },
    { name: 'biceps', emoji: '\u{1F4AA}' },
    { name: 'sure', emoji: '\u{261D}' },
    { name: 'fu', emoji: '\u{1F595}' },
    { name: 'victory', emoji: '\u{270C}' },
    { name: 'fingers_', emoji: '\u{1F91E}' },
    { name: 'vulcan_salute', emoji: '\u{1F596}' },
    { name: 'call_me', emoji: '\u{1F919}' },
    { name: 'raised_hand', emoji: '\u{270B}' },
    { name: 'ok', emoji: '\u{1F44C}' },
    { name: 'thumbs_up', emoji: '\u{1F44D}' },
    { name: 'thumbs_down', emoji: '\u{1F44E}' },
    { name: 'raised_fist', emoji: '\u{270A}' },
    { name: 'fist', emoji: '\u{1F44A}' },
    { name: 'left_fist', emoji: '\u{1F91B}' },
    { name: 'right_fist', emoji: '\u{1F91C}' },
    { name: 'wave', emoji: '\u{1F44B}' },
    { name: 'love_your', emoji: '\u{1F91F}' },
    { name: 'write', emoji: '\u{270D}' },
    { name: 'clap', emoji: '\u{1F44F}' },
    { name: 'open_hands', emoji: '\u{1F450}' },
    { name: 'raising_hands', emoji: '\u{1F64C}' },
    { name: 'palms_up', emoji: '\u{1F932}' },
    { name: 'folded_hands', emoji: '\u{1F64F}' },
    { name: 'handshake', emoji: '\u{1F91D}' },
    { name: 'nail_polish', emoji: '\u{1F485}' },
    { name: 'ear', emoji: '\u{1F442}' },
    { name: 'nose', emoji: '\u{1F443}' },
    { name: 'footprints', emoji: '\u{1F463}' },
    { name: 'eyes', emoji: '\u{1F440}' },
    { name: 'eye', emoji: '\u{1F441}' },
    { name: 'brain', emoji: '\u{1F9E0}' },
    { name: 'bone', emoji: '\u{1F9B4}' },
    { name: 'tooth', emoji: '\u{1F9B7}' },
    { name: 'mouth', emoji: '\u{1F444}' },
    { name: 'kiss_mark', emoji: '\u{1F48B}' },
    { name: 'heart_beat', emoji: '\u{1F493}' },
    { name: 'revolving_hearts', emoji: '\u{1F49E}' },
    { name: 'two_hearts', emoji: '\u{1F495}' },
    { name: 'broken_heart', emoji: '\u{1F494}' },
    { name: 'heart', emoji: '\u{2764}' },
    { name: 'anger_symbol', emoji: '\u{1F4A2}' },
    { name: 'bomb', emoji: '\u{1F4A3}' },
    { name: 'collision', emoji: '\u{1F4A5}' },
    { name: 'sweat', emoji: '\u{1F4A6}' },
    { name: 'dizzy_1', emoji: '\u{1F4AB}' },
    { name: 'speech_balloon', emoji: '\u{1F4AC}' },
    { name: 'anger', emoji: '\u{1F5EF}' },
    { name: 'thought', emoji: '\u{1F4AD}' },
    { name: 'hole', emoji: '\u{1F573}' },
    { name: 'glasses', emoji: '\u{1F453}' },
    { name: 'sunglasses', emoji: '\u{1F576}' },
    { name: 'goggles', emoji: '\u{1F97D}' },
    { name: 'neck_tie', emoji: '\u{1F454}' },
    { name: 't_shirt', emoji: '\u{1F455}' },
    { name: 'jeans', emoji: '\u{1F456}' },
    { name: 'scarf', emoji: '\u{1F9E3}' },
    { name: 'gloves', emoji: '\u{1F9E4}' },
    { name: 'coat', emoji: '\u{1F9E5}' },
    { name: 'socks', emoji: '\u{1F9E6}' },
    { name: 'dress', emoji: '\u{1F457}' },
    { name: 'kimono', emoji: '\u{1F458}' },
    { name: 'bikini', emoji: '\u{1F459}' },
    { name: 'women_cloth', emoji: '\u{1F45A}' },
    { name: 'purse', emoji: '\u{1F45B}' },
    { name: 'handbag', emoji: '\u{1F45C}' },
    { name: 'clutch_bag', emoji: '\u{1F45D}' },
    { name: 'shopping_bag', emoji: '\u{1F6CD}' },
    { name: 'backpack', emoji: '\u{1F392}' },
    { name: 'man_shoe', emoji: '\u{1F45E}' },
    { name: 'running_shoe', emoji: '\u{1F45F}' },
    { name: 'hiking_boot', emoji: '\u{1F97E}' },
    { name: 'flat_shoe', emoji: '\u{1F97F}' },
    { name: 'heeled_shoe', emoji: '\u{1F460}' },
    { name: 'woman_sandal', emoji: '\u{1F461}' },
    { name: 'woman_boot', emoji: '\u{1F462}' },
    { name: 'crown', emoji: '\u{1F451}' },
    { name: 'woman_hat', emoji: '\u{1F452}' },
    { name: 'top_hat', emoji: '\u{1F3A9}' },
    { name: 'graduation_cap', emoji: '\u{1F393}' },
    { name: 'billed_cap', emoji: '\u{1F9E2}' },
    { name: 'rescue_helmet', emoji: '\u{26D1}' },
    { name: 'lipstick', emoji: '\u{1F484}' },
    { name: 'ring', emoji: '\u{1F48D}' },
    { name: 'gem_stone', emoji: '\u{1F48E}' },
    { name: 'monkey_face', emoji: '\u{1F435}' },
    { name: 'monkey', emoji: '\u{1F412}' },
    { name: 'gorilla', emoji: '\u{1F98D}' },
    { name: 'dog_face', emoji: '\u{1F436}' },
    { name: 'dog', emoji: '\u{1F415}' },
    { name: 'poodle', emoji: '\u{1F429}' },
    { name: 'wolf_face', emoji: '\u{1F43A}' },
    { name: 'fox_face', emoji: '\u{1F98A}' },
    { name: 'cat_face', emoji: '\u{1F431}' },
    { name: 'cat', emoji: '\u{1F408}' },
    { name: 'lion', emoji: '\u{1F981}' },
    { name: 'tiger_face', emoji: '\u{1F42F}' },
    { name: 'tiger', emoji: '\u{1F405}' },
    { name: 'leopard', emoji: '\u{1F406}' },
    { name: 'horse_face', emoji: '\u{1F434}' },
    { name: 'horse', emoji: '\u{1F40E}' },
    { name: 'unicorn', emoji: '\u{1F984}' },
    { name: 'zebra', emoji: '\u{1F993}' },
    { name: 'deer', emoji: '\u{1F98C}' },
    { name: 'cow_face', emoji: '\u{1F42E}' },
    { name: 'ox', emoji: '\u{1F402}' },
    { name: 'water_buffalo', emoji: '\u{1F403}' },
    { name: 'cow', emoji: '\u{1F404}' },
    { name: 'pig_face', emoji: '\u{1F437}' },
    { name: 'pig', emoji: '\u{1F416}' },
    { name: 'boar', emoji: '\u{1F417}' },
    { name: 'pig_nose', emoji: '\u{1F43D}' },
    { name: 'ram', emoji: '\u{1F40F}' },
    { name: 'ewe', emoji: '\u{1F411}' },
    { name: 'goat', emoji: '\u{1F410}' },
    { name: 'camel', emoji: '\u{1F42A}' },
    { name: 'camel_2', emoji: '\u{1F42B}' },
    { name: 'llama', emoji: '\u{1F999}' },
    { name: 'giraffe', emoji: '\u{1F992}' },
    { name: 'elephant', emoji: '\u{1F418}' },
    { name: 'rhinoceros', emoji: '\u{1F98F}' },
    { name: 'hippopotamus', emoji: '\u{1F99B}' },
    { name: 'mouse_face', emoji: '\u{1F42D}' },
    { name: 'mouse', emoji: '\u{1F401}' },
    { name: 'rat', emoji: '\u{1F400}' },
    { name: 'hamster', emoji: '\u{1F439}' },
    { name: 'rabbit_face', emoji: '\u{1F430}' },
    { name: 'rabbit', emoji: '\u{1F407}' },
    { name: 'chipmunk', emoji: '\u{1F43F}' },
    { name: 'hedgehog', emoji: '\u{1F994}' },
    { name: 'bat', emoji: '\u{1F987}' },
    { name: 'bear_face', emoji: '\u{1F43B}' },
    { name: 'koala', emoji: '\u{1F428}' },
    { name: 'panda', emoji: '\u{1F43C}' },
    { name: 'kangaroo', emoji: '\u{1F998}' },
    { name: 'badger', emoji: '\u{1F9A1}' },
    { name: 'paw', emoji: '\u{1F43E}' },
    { name: 'turkey', emoji: '\u{1F983}' },
    { name: 'chicken', emoji: '\u{1F414}' },
    { name: 'rooster', emoji: '\u{1F413}' },
    { name: 'chick', emoji: '\u{1F423}' },
    { name: 'chick_1', emoji: '\u{1F424}' },
    { name: 'chick_2', emoji: '\u{1F425}' },
    { name: 'bird', emoji: '\u{1F426}' },
    { name: 'penguin', emoji: '\u{1F427}' },
    { name: 'dove', emoji: '\u{1F54A}' },
    { name: 'eagle', emoji: '\u{1F985}' },
    { name: 'duck', emoji: '\u{1F986}' },
    { name: 'owl', emoji: '\u{1F989}' },
    { name: 'peacock', emoji: '\u{1F99A}' },
    { name: 'parrot', emoji: '\u{1F99C}' },
    { name: 'frog', emoji: '\u{1F438}' },
    { name: 'crocodile', emoji: '\u{1F40A}' },
    { name: 'turtle', emoji: '\u{1F422}' },
    { name: 'lizard', emoji: '\u{1F98E}' },
    { name: 'snake', emoji: '\u{1F40D}' },
    { name: 'dragon_face', emoji: '\u{1F432}' },
    { name: 'dragon', emoji: '\u{1F409}' },
    { name: 'sauropod', emoji: '\u{1F995}' },
    { name: 'spouting_whale', emoji: '\u{1F433}' },
    { name: 'whale', emoji: '\u{1F40B}' },
    { name: 'dolphin', emoji: '\u{1F42C}' },
    { name: 'fish', emoji: '\u{1F41F}' },
    { name: 'fish_1', emoji: '\u{1F420}' },
    { name: 'blowfish', emoji: '\u{1F421}' },
    { name: 'shark', emoji: '\u{1F988}' },
    { name: 'octopus', emoji: '\u{1F419}' },
    { name: 'spiral_shell', emoji: '\u{1F41A}' },
    { name: 'butterfly', emoji: '\u{1F98B}' },
    { name: 'bug', emoji: '\u{1F41B}' },
    { name: 'ant', emoji: '\u{1F41C}' },
    { name: 'honeybee', emoji: '\u{1F41D}' },
    { name: 'beetle', emoji: '\u{1F41E}' },
    { name: 'cricket_1', emoji: '\u{1F997}' },
    { name: 'spider', emoji: '\u{1F577}' },
    { name: 'spider_web', emoji: '\u{1F578}' },
    { name: 'scorpion', emoji: '\u{1F982}' },
    { name: 'mosquito', emoji: '\u{1F99F}' },
    { name: 'bouquet', emoji: '\u{1F490}' },
    { name: 'cherry_blossom', emoji: '\u{1F338}' },
    { name: 'rosette', emoji: '\u{1F3F5}' },
    { name: 'rose', emoji: '\u{1F339}' },
    { name: 'wilted_flower', emoji: '\u{1F940}' },
    { name: 'hibiscus', emoji: '\u{1F33A}' },
    { name: 'sunflower', emoji: '\u{1F33B}' },
    { name: 'blossom', emoji: '\u{1F33C}' },
    { name: 'tulip', emoji: '\u{1F337}' },
    { name: 'seedling', emoji: '\u{1F331}' },
    { name: 'tree', emoji: '\u{1F332}' },
    { name: 'palm_tree', emoji: '\u{1F334}' },
    { name: 'cactus', emoji: '\u{1F335}' },
    { name: 'herb', emoji: '\u{1F33F}' },
    { name: 'shamrock', emoji: '\u{2618}' },
    { name: 'maple_leaf', emoji: '\u{1F341}' },
    { name: 'fallen_leaf', emoji: '\u{1F342}' },
    { name: 'leaf_in_wind', emoji: '\u{1F343}' },
    { name: 'grapes', emoji: '\u{1F347}' },
    { name: 'melon', emoji: '\u{1F348}' },
    { name: 'watermelon', emoji: '\u{1F349}' },
    { name: 'tangerine', emoji: '\u{1F34A}' },
    { name: 'lemon', emoji: '\u{1F34B}' },
    { name: 'banana', emoji: '\u{1F34C}' },
    { name: 'pineapple', emoji: '\u{1F34D}' },
    { name: 'mango', emoji: '\u{1F96D}' },
    { name: 'apple', emoji: '\u{1F34E}' },
    { name: 'pear', emoji: '\u{1F350}' },
    { name: 'peach', emoji: '\u{1F351}' },
    { name: 'cherries', emoji: '\u{1F352}' },
    { name: 'strawberry', emoji: '\u{1F353}' },
    { name: 'kiwi_fruit', emoji: '\u{1F95D}' },
    { name: 'tomatoes', emoji: '\u{1F345}' },
    { name: 'coconut', emoji: '\u{1F965}' },
    { name: 'avocado', emoji: '\u{1F951}' },
    { name: 'eggplant', emoji: '\u{1F346}' },
    { name: 'potato', emoji: '\u{1F954}' },
    { name: 'carrot', emoji: '\u{1F955}' },
    { name: 'pepper', emoji: '\u{1F336}' },
    { name: 'cucumber', emoji: '\u{1F952}' },
    { name: 'leafy_green', emoji: '\u{1F96C}' },
    { name: 'broccoli', emoji: '\u{1F966}' },
    { name: 'mushroom', emoji: '\u{1F344}' },
    { name: 'peanuts', emoji: '\u{1F95C}' },
    { name: 'chestnut', emoji: '\u{1F330}' },
    { name: 'bread', emoji: '\u{1F35E}' },
    { name: 'croissant', emoji: '\u{1F950}' },
    { name: 'baguette', emoji: '\u{1F956}' },
    { name: 'pretzel', emoji: '\u{1F968}' },
    { name: 'pancakes', emoji: '\u{1F95E}' },
    { name: 'cheese', emoji: '\u{1F9C0}' },
    { name: 'meat', emoji: '\u{1F356}' },
    { name: 'poultry', emoji: '\u{1F357}' },
    { name: 'meat_cut', emoji: '\u{1F969}' },
    { name: 'bacon', emoji: '\u{1F953}' },
    { name: 'hamburger', emoji: '\u{1F354}' },
    { name: 'fries', emoji: '\u{1F35F}' },
    { name: 'pizza', emoji: '\u{1F355}' },
    { name: 'hot_dog', emoji: '\u{1F32D}' },
    { name: 'sandwich', emoji: '\u{1F96A}' },
    { name: 'taco', emoji: '\u{1F32E}' },
    { name: 'burrito', emoji: '\u{1F32F}' },
    { name: 'flatbread', emoji: '\u{1F959}' },
    { name: 'egg', emoji: '\u{1F95A}' },
    { name: 'cooking', emoji: '\u{1F373}' },
    { name: 'pan_of_food', emoji: '\u{1F958}' },
    { name: 'food', emoji: '\u{1F372}' },
    { name: 'spoon', emoji: '\u{1F963}' },
    { name: 'salad', emoji: '\u{1F957}' },
    { name: 'popcorn', emoji: '\u{1F37F}' },
    { name: 'salt', emoji: '\u{1F9C2}' },
    { name: 'canned_food', emoji: '\u{1F96B}' },
    { name: 'bento_box', emoji: '\u{1F371}' },
    { name: 'rice_ball', emoji: '\u{1F359}' },
    { name: 'cooked_rice', emoji: '\u{1F35A}' },
    { name: 'curry_rice', emoji: '\u{1F35B}' },
    { name: 'steaming_bowl', emoji: '\u{1F35C}' },
    { name: 'spaghetti', emoji: '\u{1F35D}' },
    { name: 'roasted_sweet_potato', emoji: '\u{1F360}' },
    { name: 'oden', emoji: '\u{1F362}' },
    { name: 'sushi', emoji: '\u{1F363}' },
    { name: 'fried_shrimp', emoji: '\u{1F364}' },
    { name: 'dango', emoji: '\u{1F361}' },
    { name: 'dumpling', emoji: '\u{1F95F}' },
    { name: 'fortune_cookie', emoji: '\u{1F960}' },
    { name: 'takeout_box', emoji: '\u{1F961}' },
    { name: 'crab', emoji: '\u{1F980}' },
    { name: 'shrimp', emoji: '\u{1F990}' },
    { name: 'squid', emoji: '\u{1F991}' },
    { name: 'soft_ice_cream', emoji: '\u{1F366}' },
    { name: 'shaved_ice', emoji: '\u{1F367}' },
    { name: 'ice_cream', emoji: '\u{1F368}' },
    { name: 'doughnut', emoji: '\u{1F369}' },
    { name: 'cookie', emoji: '\u{1F36A}' },
    { name: 'birthday_cake', emoji: '\u{1F382}' },
    { name: 'shortcake', emoji: '\u{1F370}' },
    { name: 'pie', emoji: '\u{1F967}' },
    { name: 'chocolate_bar', emoji: '\u{1F36B}' },
    { name: 'candy', emoji: '\u{1F36C}' },
    { name: 'lollipop', emoji: '\u{1F36D}' },
    { name: 'custard', emoji: '\u{1F36E}' },
    { name: 'honey_pot', emoji: '\u{1F36F}' },
    { name: 'baby_bottle', emoji: '\u{1F37C}' },
    { name: 'milk', emoji: '\u{1F95B}' },
    { name: 'beverage', emoji: '\u{2615}' },
    { name: 'teacup', emoji: '\u{1F375}' },
    { name: 'sake', emoji: '\u{1F376}' },
    { name: 'wine', emoji: '\u{1F377}' },
    { name: 'cocktail', emoji: '\u{1F378}' },
    { name: 'tropical_drink', emoji: '\u{1F379}' },
    { name: 'beer_mug', emoji: '\u{1F37A}' },
    { name: 'clinking_glasses', emoji: '\u{1F942}' },
    { name: 'tumbler_glass', emoji: '\u{1F943}' },
    { name: 'chopsticks', emoji: '\u{1F962}' },
    { name: 'cutlery', emoji: '\u{1F37D}' },
    { name: 'fork_knife', emoji: '\u{1F374}' },
    { name: 'spoon_1', emoji: '\u{1F944}' },
    { name: 'kitchen_knife', emoji: '\u{1F52A}' },
    { name: 'amphora', emoji: '\u{1F3FA}' },
    { name: 'globe_africa', emoji: '\u{1F30D}' },
    { name: 'snow_capped', emoji: '\u{1F3D4}' },
    { name: 'mountain', emoji: '\u{26F0}' },
    { name: 'volcano', emoji: '\u{1F30B}' },
    { name: 'camping', emoji: '\u{1F3D5}' },
    { name: 'beach', emoji: '\u{1F3D6}' },
    { name: 'desert', emoji: '\u{1F3DC}' },
    { name: 'stadium', emoji: '\u{1F3DF}' },
    { name: 'building', emoji: '\u{1F3DB}' },
    { name: 'houses', emoji: '\u{1F3D8}' },
    { name: 'house', emoji: '\u{1F3E0}' },
    { name: 'home', emoji: '\u{1F3E1}' },
    { name: 'office_building', emoji: '\u{1F3E2}' },
    { name: 'post_office', emoji: '\u{1F3E4}' },
    { name: 'hospital', emoji: '\u{1F3E5}' },
    { name: 'bank', emoji: '\u{1F3E6}' },
    { name: 'hotel', emoji: '\u{1F3E8}' },
    { name: 'convenience_store', emoji: '\u{1F3EA}' },
    { name: 'school', emoji: '\u{1F3EB}' },
    { name: 'department_store', emoji: '\u{1F3EC}' },
    { name: 'factory', emoji: '\u{1F3ED}' },
    { name: 'Japanese_castle', emoji: '\u{1F3EF}' },
    { name: 'castle', emoji: '\u{1F3F0}' },
    { name: 'statue_of_Liberty', emoji: '\u{1F5FD}' },
    { name: 'church', emoji: '\u{26EA}' },
    { name: 'mosque', emoji: '\u{1F54C}' },
    { name: 'synagogue', emoji: '\u{1F54D}' },
    { name: 'fountain', emoji: '\u{26F2}' },
    { name: 'tent', emoji: '\u{26FA}' },
    { name: 'hot_springs', emoji: '\u{2668}' },
    { name: 'ferris_wheel', emoji: '\u{1F3A1}' },
    { name: 'roller_coaster', emoji: '\u{1F3A2}' },
    { name: 'barber_pole', emoji: '\u{1F488}' },
    { name: 'circus_tent', emoji: '\u{1F3AA}' },
    { name: 'railway_car', emoji: '\u{1F683}' },
    { name: 'train', emoji: '\u{1F686}' },
    { name: 'metro', emoji: '\u{1F687}' },
    { name: 'light_rail', emoji: '\u{1F688}' },
    { name: 'station', emoji: '\u{1F689}' },
    { name: 'tram', emoji: '\u{1F68A}' },
    { name: 'monorail', emoji: '\u{1F69D}' },
    { name: 'railway', emoji: '\u{1F69E}' },
    { name: 'tram_1', emoji: '\u{1F68B}' },
    { name: 'bus', emoji: '\u{1F68C}' },
    { name: 'oncoming_bus', emoji: '\u{1F68D}' },
    { name: 'ambulance', emoji: '\u{1F691}' },
    { name: 'fire_engine', emoji: '\u{1F692}' },
    { name: 'taxi', emoji: '\u{1F695}' },
    { name: 'oncoming_taxi', emoji: '\u{1F696}' },
    { name: 'tractor', emoji: '\u{1F69C}' },
    { name: 'bicycle', emoji: '\u{1F6B2}' },
    { name: 'kick_scooter', emoji: '\u{1F6F4}' },
    { name: 'motor_scooter', emoji: '\u{1F6F5}' },
    { name: 'motorway', emoji: '\u{1F6E3}' },
    { name: 'railway_track', emoji: '\u{1F6E4}' },
    { name: 'stop_sign', emoji: '\u{1F6D1}' },
    { name: 'construction', emoji: '\u{1F6A7}' },
    { name: 'anchor', emoji: '\u{2693}' },
    { name: 'sailboat', emoji: '\u{26F5}' },
    { name: 'canoe', emoji: '\u{1F6F6}' },
    { name: 'speedboat', emoji: '\u{1F6A4}' },
    { name: 'passenger_ship', emoji: '\u{1F6F3}' },
    { name: 'ferry', emoji: '\u{26F4}' },
    { name: 'motor_boat', emoji: '\u{1F6E5}' },
    { name: 'ship', emoji: '\u{1F6A2}' },
    { name: 'airplane', emoji: '\u{2708}' },
    { name: 'small_airplane', emoji: '\u{1F6E9}' },
    { name: 'departure', emoji: '\u{1F6EB}' },
    { name: 'arrival', emoji: '\u{1F6EC}' },
    { name: 'seat', emoji: '\u{1F4BA}' },
    { name: 'helicopter', emoji: '\u{1F681}' },
    { name: 'cableway', emoji: '\u{1F6A0}' },
    { name: 'tramway', emoji: '\u{1F6A1}' },
    { name: 'satellite_1', emoji: '\u{1F6F0}' },
    { name: 'rocket', emoji: '\u{1F680}' },
    { name: 'flying_saucer', emoji: '\u{1F6F8}' },
    { name: 'hourglass', emoji: '\u{231B}' },
    { name: 'hourglass_1', emoji: '\u{23F3}' },
    { name: 'watch', emoji: '\u{231A}' },
    { name: 'alarm_clock', emoji: '\u{23F0}' },
    { name: 'stopwatch', emoji: '\u{23F1}' },
    { name: 'new_moon', emoji: '\u{1F311}' },
    { name: 'thermometer', emoji: '\u{1F321}' },
    { name: 'sun', emoji: '\u{2600}' },
    { name: 'star', emoji: '\u{2B50}' },
    { name: 'glowing_star', emoji: '\u{1F31F}' },
    { name: 'cloud', emoji: '\u{2601}' },
    { name: 'tornado', emoji: '\u{1F32A}' },
    { name: 'cyclone', emoji: '\u{1F300}' },
    { name: 'rainbow', emoji: '\u{1F308}' },
    { name: 'closed_umbrella', emoji: '\u{1F302}' },
    { name: 'umbrella', emoji: '\u{2602}' },
    { name: 'high_voltage', emoji: '\u{26A1}' },
    { name: 'snowflake', emoji: '\u{2744}' },
    { name: 'comet', emoji: '\u{2604}' },
    { name: 'fire', emoji: '\u{1F525}' },
    { name: 'droplet', emoji: '\u{1F4A7}' },
    { name: 'jack_o_lantern', emoji: '\u{1F383}' },
    { name: 'christmas_tree', emoji: '\u{1F384}' },
    { name: 'sparkles', emoji: '\u{2728}' },
    { name: 'balloon', emoji: '\u{1F388}' },
    { name: 'party_popper', emoji: '\u{1F389}' },
    { name: 'wind_chime', emoji: '\u{1F390}' },
    { name: 'ribbon', emoji: '\u{1F380}' },
    { name: 'gift', emoji: '\u{1F381}' },
    { name: 'tickets', emoji: '\u{1F39F}' },
    { name: 'medal', emoji: '\u{1F396}' },
    { name: 'trophy', emoji: '\u{1F3C6}' },
    { name: 'medal_4', emoji: '\u{1F3C5}' },
    { name: 'medal_1', emoji: '\u{1F947}' },
    { name: 'medal_2', emoji: '\u{1F948}' },
    { name: 'medal_3', emoji: '\u{1F949}' },
    { name: 'soccer_ball', emoji: '\u{26BD}' },
    { name: 'baseball', emoji: '\u{26BE}' },
    { name: 'softball', emoji: '\u{1F94E}' },
    { name: 'basketball', emoji: '\u{1F3C0}' },
    { name: 'volleyball', emoji: '\u{1F3D0}' },
    { name: 'american_football', emoji: '\u{1F3C8}' },
    { name: 'rugby', emoji: '\u{1F3C9}' },
    { name: 'tennis', emoji: '\u{1F3BE}' },
    { name: 'bowling', emoji: '\u{1F3B3}' },
    { name: 'cricket', emoji: '\u{1F3CF}' },
    { name: 'hockey', emoji: '\u{1F3D1}' },
    { name: 'ice_hockey', emoji: '\u{1F3D2}' },
    { name: 'ping_pong', emoji: '\u{1F3D3}' },
    { name: 'badminton', emoji: '\u{1F3F8}' },
    { name: 'boxing_glove', emoji: '\u{1F94A}' },
    { name: 'goal_net', emoji: '\u{1F945}' },
    { name: 'flag_in_hole', emoji: '\u{26F3}' },
    { name: 'ice_skate', emoji: '\u{26F8}' },
    { name: 'fishing_pole', emoji: '\u{1F3A3}' },
    { name: 'skis', emoji: '\u{1F3BF}' },
    { name: 'sled', emoji: '\u{1F6F7}' },
    { name: 'direct_hit', emoji: '\u{1F3AF}' },
    { name: 'crystal_ball', emoji: '\u{1F52E}' },
    { name: 'video_game', emoji: '\u{1F3AE}' },
    { name: 'joystick', emoji: '\u{1F579}' },
    { name: 'game_die', emoji: '\u{1F3B2}' },
    { name: 'chess_pawn', emoji: '\u{265F}' },
    { name: 'thread', emoji: '\u{1F9F5}' },
    { name: 'yarn', emoji: '\u{1F9F6}' },
    { name: 'megaphone', emoji: '\u{1F4E3}' },
    { name: 'postal_horn', emoji: '\u{1F4EF}' },
    { name: 'bell', emoji: '\u{1F514}' },
    { name: 'microphone', emoji: '\u{1F3A4}' },
    { name: 'headphone', emoji: '\u{1F3A7}' },
    { name: 'saxophone', emoji: '\u{1F3B7}' },
    { name: 'guitar', emoji: '\u{1F3B8}' },
    { name: 'musical_keyboard', emoji: '\u{1F3B9}' },
    { name: 'trumpet', emoji: '\u{1F3BA}' },
    { name: 'violin', emoji: '\u{1F3BB}' },
    { name: 'drum', emoji: '\u{1F941}' },
    { name: 'mobile', emoji: '\u{1F4F1}' },
    { name: 'telephone', emoji: '\u{260E}' },
    { name: 'pager', emoji: '\u{1F4DF}' },
    { name: 'battery', emoji: '\u{1F50B}' },
    { name: 'laptop', emoji: '\u{1F4BB}' },
    { name: 'desktop', emoji: '\u{1F5A5}' },
    { name: 'keyboard', emoji: '\u{2328}' },
    { name: 'mouse', emoji: '\u{1F5B1}' },
    { name: 'trackball', emoji: '\u{1F5B2}' },
    { name: 'camera', emoji: '\u{1F4F7}' },
    { name: 'candle', emoji: '\u{1F56F}' },
    { name: 'bulb', emoji: '\u{1F4A1}' },
    { name: 'flashlight', emoji: '\u{1F526}' },
    { name: 'notebook', emoji: '\u{1F4D4}' },
    { name: 'book', emoji: '\u{1F4D6}' },
    { name: 'books', emoji: '\u{1F4DA}' },
    { name: 'notebook_1', emoji: '\u{1F4D3}' },
    { name: 'ledger', emoji: '\u{1F4D2}' },
    { name: 'bookmark', emoji: '\u{1F516}' },
    { name: 'label', emoji: '\u{1F3F7}' },
    { name: 'money_bag', emoji: '\u{1F4B0}' },
    { name: 'yen', emoji: '\u{1F4B4}' },
    { name: 'dollar', emoji: '\u{1F4B5}' },
    { name: 'euro', emoji: '\u{1F4B6}' },
    { name: 'pound', emoji: '\u{1F4B7}' },
    { name: 'credit_card', emoji: '\u{1F4B3}' },
    { name: 'receipt', emoji: '\u{1F9FE}' },
    { name: 'dollar_sign', emoji: '\u{1F4B2}' },
    { name: 'envelope', emoji: '\u{2709}' },
    { name: 'email', emoji: '\u{1F4E7}' },
    { name: 'outbox', emoji: '\u{1F4E4}' },
    { name: 'inbox', emoji: '\u{1F4E5}' },
    { name: 'package', emoji: '\u{1F4E6}' },
    { name: 'black_nib', emoji: '\u{2712}' },
    { name: 'fountain_pen', emoji: '\u{1F58B}' },
    { name: 'pen', emoji: '\u{1F58A}' },
    { name: 'paintbrush', emoji: '\u{1F58C}' },
    { name: 'memo', emoji: '\u{1F4DD}' },
    { name: 'briefcase', emoji: '\u{1F4BC}' },
    { name: 'file_folder', emoji: '\u{1F4C1}' },
    { name: 'calendar', emoji: '\u{1F4C5}' },
    { name: 'card_index', emoji: '\u{1F4C7}' },
    { name: 'clipboard', emoji: '\u{1F4CB}' },
    { name: 'pushpin', emoji: '\u{1F4CC}' },
    { name: 'paperclip', emoji: '\u{1F4CE}' },
    { name: 'ruler', emoji: '\u{1F4CF}' },
    { name: 'scissors', emoji: '\u{2702}' },
    { name: 'cabinet', emoji: '\u{1F5C4}' },
    { name: 'wastebasket', emoji: '\u{1F5D1}' },
    { name: 'locked', emoji: '\u{1F512}' },
    { name: 'unlocked', emoji: '\u{1F513}' },
    { name: 'key', emoji: '\u{1F511}' },
    { name: 'old_key', emoji: '\u{1F5DD}' },
    { name: 'hammer', emoji: '\u{1F528}' },
    { name: 'pick', emoji: '\u{26CF}' },
    { name: 'wrench', emoji: '\u{1F6E0}' },
    { name: 'dagger', emoji: '\u{1F5E1}' },
    { name: 'swords', emoji: '\u{2694}' },
    { name: 'pistol', emoji: '\u{1F52B}' },
    { name: 'bow', emoji: '\u{1F3F9}' },
    { name: 'shield', emoji: '\u{1F6E1}' },
    { name: 'wrench_1', emoji: '\u{1F527}' },
    { name: 'nut_bolt', emoji: '\u{1F529}' },
    { name: 'gear', emoji: '\u{2699}' },
    { name: 'scale', emoji: '\u{2696}' },
    { name: 'link', emoji: '\u{1F517}' },
    { name: 'chains', emoji: '\u{26D3}' },
    { name: 'microscope', emoji: '\u{1F52C}' },
    { name: 'telescope', emoji: '\u{1F52D}' },
    { name: 'satellite', emoji: '\u{1F4E1}' },
    { name: 'syringe', emoji: '\u{1F489}' },
    { name: 'pill', emoji: '\u{1F48A}' },
    { name: 'door', emoji: '\u{1F6AA}' },
    { name: 'bed', emoji: '\u{1F6CF}' },
    { name: 'couch_lamp', emoji: '\u{1F6CB}' },
    { name: 'toilet', emoji: '\u{1F6BD}' },
    { name: 'shower', emoji: '\u{1F6BF}' },
    { name: 'bathtub', emoji: '\u{1F6C1}' },
    ];
  constructor(private router: Router) {}
  ngOnInit(): void {
  }
  e_comment(emoji: string): void {
    alert(`emoji${emoji}`)
    // console.log("emoji: ",emoji)
    // this.router.navigate(['/comments', emoji]);
    }
  // this.router.navigate(['/comments', encodeURIComponent(emoji)]);
  
}
